### ISSUE TITLE
Feature request: Seed value concept

### ISSUE THREAD

**Issue by ojwenzel** [bethgelab/imagecorruptions#11]
For usage in science, reproducibility of the corruption types would be very helpful. Thus, some sort of seed value concept would be a great feature.

**Comment by ojwenzel** [comment]
I tried setting the seed both, in numpy and pytorch in the following example. Resulting image1 and image2 where still different. 

```
# PARAMETERS
idx = 0

# get an image from pytorch CIFAR10 dataset
image1, label1 = testset[idx]
image2, label2 = testset[idx]

# compute euclidean distance
distance = torch.sqrt(((image1-image2)**2).sum())

# show images
imshow(torchvision.utils.make_grid(image1-image2, normalize=True))

# print labels
print(classes[label])

# print distance
print('distance: {}'.format(distance))
```

**Comment by ojwenzel** [comment]
Resetting the numpy seed before calling the corruption function does yield reproducible results for all corruption types :)

**Comment by Hvitgar** [comment]
For clarification (if somebody else wants to use that as a workaround for the time being):
```python3
np.random.seed(131213)
corrupt(img, corruption_name=corruption_name, severity=severity)
```
yields a corrupted image that is reproducible (with the same seed)
