### ISSUE TITLE
COCO-C

### ISSUE THREAD

**Issue by ternaus** [bethgelab/imagecorruptions#12]
How exactly do you apply the library to get exactly the same COCO-C dataset as was used in https://arxiv.org/abs/1907.07484 ?

**Comment by michaelisc** [comment]
We apply the corruption on each image directly after loading it with:
```
img = corrupt(img, severity=corruption_severity, corruption_name=corruption_ name)
```

See [our implementation](https://github.com/open-mmlab/mmdetection/blob/d1c71db791e2e8279e1a3214e8217a36495b22a0/tools/test_robustness.py#L355) in mmdetection for details. Here is also the [link](https://github.com/bethgelab/mmdetection/blob/d1c85a9d756670aabe43cbda3f89eb1097666ef6/mmdet/datasets/custom.py#L284) to the correct line in our original pull request. The new pipeline based dataloader can be a bit hard to understand if you look at it for the first time.
