### ISSUE TITLE
Global warnings filter should be restricted to a single module

### ISSUE THREAD

**Issue by MrLobs** [bethgelab/imagecorruptions#15]
This warnings filter silently kills all warnings in all packages ([link](https://github.com/bethgelab/imagecorruptions/blob/55338d131ebb097ec277fd82ac80c2e27cb410f9/imagecorruptions/corruptions.py#L19))

Can it be narrowed down to `warnings.filterwarnings('ignore', module='imagecorruptions.corruptions')`?

**Comment by Hvitgar** [comment]
Thanks, I will change it accordingly
