### ISSUE TITLE
How can I use your library function to achieve the snow effect that the first image in your paper simulated？

### ISSUE THREAD

**Issue by xiaoachen98** [bethgelab/imagecorruptions#17]
The first picture is about the game of Thrones, and the snow effect it simulates is very real. However, I cannot achieve this effect by using the function you provided. I would like to ask whether you have used additional rendering technology to achieve this effect.Because I want to simulate snow falling on Cityscapes data sets, maybe you guys have any ideas that might be useful?

**Comment by Hvitgar** [comment]
This effect was not created with the code in this repository. The image serves as a teaser, the snow was created using [this](https://ieeexplore.ieee.org/document/8917367). Sadly, to my knowledge their code/toolbox is not publicly available.
