### ISSUE TITLE
Cityscapes 2D object detection

### ISSUE THREAD

**Issue by ManoharSai2000** [bethgelab/imagecorruptions#19]
Where can I find the annotations for Cityscapes 2D object detection?

Thanks in Advance!

**Comment by Hvitgar** [comment]
this package just provides functionality for corrupting images. Altering the corresponding annotation files is currently not supported.

**Comment by ManoharSai2000** [comment]
Thanks for the reply!

This is not for modification purposes. Just asking for help in finding them!

Thank You
